name: Install NGINX on EKS
on: [push]
jobs:
  install_nginx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1  # replace with your AWS region
   
    - name: Install AWS EKS CLI
      run: |
        curl --silent --location "https://amazonaws.com/eks/latest/download/aws-iam-authenticator" -o /usr/local/bin/aws-iam-authenticator
        chmod +x /usr/local/bin/aws-iam-authenticator
        echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bash_profile
        source ~/.bash_profile
        curl --silent --location "https://amazonaws.com/eks/latest/download/kubectl" -o /usr/local/bin/kubectl
        chmod +x /usr/local/bin/kubectl
   
    - name: Connect to EKS cluster
      run: |
        aws eks --region us-west-1 update-kubeconfig --name eks-mundos-e
   
    - name: Install NGINX
      run: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.35.0/deploy/static/provider/aws/deploy.yaml
